name: Run tests
on:
  - push
  - pull_request
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dependencies
        run: sudo apt install libcurl4-openssl-dev
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/work/_temp/Library
          key: ${{ hashFiles('install_ci.R') }}-${{ hashFiles('DESCRIPTION') }}
      - name: Install package
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          Rscript install_ci.R
      - name: TestThat
        run: |
          Rscript -e 'packageVersion("inspectEHR")'
          Rscript -e 'testthat::test_file("tests/testthat/test_perform_evaluation.R", stop_on_failure=TRUE)'
